# 운영 서버 전용 Compose 파일
# /opt/backtest/backend/compose.yaml로 복사하여 사용
# 사용법:
#   1. 이 파일을 서버의 /opt/backtest/backend/ 디렉터리에 복사
#   2. 같은 디렉터리에 .env 파일 준비
#   3. docker compose -f compose.yaml up -d

name: backtest-prod

services:
  backtest_be_fast:
    image: ghcr.io/capstone-backtest/backtest/backtest-be-fast:latest
    container_name: backtest_be_fast_prod
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      # 호스트의 MySQL 사용
      - DATABASE_HOST=localhost
      - DATABASE_PORT=3306
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backtest_be_spring:
    image: ghcr.io/capstone-backtest/backtest/backtest-be-spring:latest
    container_name: backtest_be_spring_prod
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      # 호스트의 MySQL과 Redis 사용
      - SPRING_DATASOURCE_HOST=localhost
      - SPRING_DATASOURCE_PORT=3306
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME:-root}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SPRING_REDIS_HOST=localhost
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080

  backtest_fe:
    image: ghcr.io/capstone-backtest/backtest/backtest-fe:latest
    container_name: backtest_fe_prod
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    depends_on:
      backtest_be_fast:
        condition: service_healthy
      backtest_be_spring:
        condition: service_started
