services:
  backend:
    build: ./backend
    ports:
      - "8001:8000"
    environment:
      - PYTHONPATH=/app
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "8082:80"
    depends_on:
      - backend
