version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: bt_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: stock_community
      MYSQL_USER: bt_user
      MYSQL_PASSWORD: bt_pass
    volumes:
      - ./database:/docker-entrypoint-initdb.d:ro
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:7-alpine
    container_name: bt_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
