services:
  fastapi:
    build: ./fastapi
    ports:
      - "8001:8000"
    environment:
      - PYTHONPATH=/app
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - ./fastapi/.env

  frontend:
    build: ./frontend
    depends_on:
      - fastapi
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
