services:
  backend:
    build: ./backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - PYTHONPATH=/app
      - APP_VERSION=1.0.0-dev
      - ENVIRONMENT=development
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    working_dir: /app
    ports:
      - "5174:5174"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - API_PROXY_TARGET=http://backend:8000
    depends_on:
      - backend
  
  # 프론트엔드 테스트 실행을 위한 별도 서비스
  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run test:run
    profiles:
      - test

  # 백엔드 테스트 실행을 위한 별도 서비스
  backend-test:
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: python -m pytest tests/ -v
    environment:
      - PYTHONPATH=/app
    profiles:
      - test
