services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - PYTHONPATH=/app
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - API_PROXY_TARGET=http://backend:8000
    depends_on:
      - backend
