services:
  mysql:
    image: mysql:8.0
    container_name: bt_mysql_prod
    restart: unless-stopped
    command: ["--default-authentication-plugin=mysql_native_password"]
    networks:
      - backtest-net
    env_file:
      - ../.env
    volumes:
      - ../database:/docker-entrypoint-initdb.d:ro
      - backtest_db_data_prod:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p\"${MYSQL_ROOT_PASSWORD}\" >/dev/null 2>&1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: bt_redis_prod
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - backtest_redis_data_prod:/data
    networks:
      - backtest-net
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backtest_be_fast:
    image: ghcr.io/capstone-backtest/backtest/backtest-be-fast:latest
    container_name: backtest_be_fast_prod
    restart: unless-stopped
    networks:
      - backtest-net
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DEBUG=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  backtest_be_spring:
    image: ghcr.io/capstone-backtest/backtest/backtest-be-spring:latest
    container_name: backtest_be_spring_prod
    restart: unless-stopped
    networks:
      - backtest-net
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    environment:
      - SPRING_DATASOURCE_HOST=mysql
      - SPRING_DATASOURCE_PORT=3306
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_PROFILES_ACTIVE=prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  backtest_fe:
    image: ghcr.io/capstone-backtest/backtest/backtest-fe:latest
    container_name: backtest_fe_prod
    restart: unless-stopped
    networks:
      - backtest-net
    depends_on:
      backtest_be_fast:
        condition: service_healthy
      backtest_be_spring:
        condition: service_healthy
    ports:
      - "80:80"   # Nginx serves on port 80
      - "443:443" # HTTPS
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  backtest_db_data_prod:
  backtest_redis_data_prod:

networks:
  backtest-net:
    name: backtest-network-prod
    driver: bridge
