version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: bt_mysql_test
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: testpass
      MYSQL_DATABASE: stock_community
      MYSQL_USER=bt_user
      MYSQL_PASSWORD=test_pass
    volumes:
      - ../database:/docker-entrypoint-initdb.d:ro
      - backtest_db_data_test:/var/lib/mysql
    ports:
      - "3310:3306"

  redis:
    image: redis:7-alpine
    container_name: bt_redis_test
    ports:
      - "6380:6379"
    volumes:
      - backtest_redis_data_test:/data

  # Application services are the same as dev but use test images/names
  backtest_be_fast:
    build:
      context: ../backtest_be_fast
      dockerfile: Dockerfile
    image: backtest-be-fast:test
    container_name: backtest_be_fast_test
    networks:
      - backtest-net
    depends_on:
      - mysql
    ports:
      - "8010:8000"
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=bt_user
      - DATABASE_PASSWORD=test_pass
      - DATABASE_NAME=stock_community
    volumes:
      - ../backtest_be_fast:/app
    command: ["python", "run_server.py"]

  backtest_be_spring:
    build:
      context: ../backtest_be_spring
      dockerfile: Dockerfile
    image: backtest-be-spring:test
    container_name: backtest_be_spring_test
    networks:
      - backtest-net
    depends_on:
      - mysql
      - redis
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/stock_community?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=bt_user
      - SPRING_DATASOURCE_PASSWORD=test_pass
      - SPRING_REDIS_HOST=redis
    volumes:
      - ../backtest_be_spring:/app
    command: ["./gradlew", "bootRun"]

  backtest_fe:
    build:
      context: ../backtest_fe
      dockerfile: Dockerfile.dev
    image: backtest-fe:test
    container_name: backtest_fe_test
    networks:
      - backtest-net
    depends_on:
      - backtest_be_fast
      - backtest_be_spring
    ports:
      - "5174:5173"
    volumes:
      - ../backtest_fe:/app
      - backtest_fe_node_modules_test:/app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8010
    command: ["npm", "run", "dev"]

volumes:
  backtest_db_data_test:
  backtest_redis_data_test:
  backtest_fe_node_modules_test:

networks:
  backtest-net:
    name: backtest-network
