version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: bt_mysql_dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: stock_community
      MYSQL_USER: bt_user
      MYSQL_PASSWORD: bt_pass
    volumes:
      - ../database:/docker-entrypoint-initdb.d:ro
      - backtest_db_data_dev:/var/lib/mysql
    ports:
      - "3307:3306"

  redis:
    image: redis:7-alpine
    container_name: bt_redis_dev
    ports:
      - "6379:6379"
    volumes:
      - backtest_redis_data_dev:/data

  backtest_be_fast:
    build:
      context: ../backtest_be_fast
      dockerfile: Dockerfile
    image: backtest-be-fast:dev
    container_name: backtest_be_fast_dev
    networks:
      - backtest-net
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=bt_user
      - DATABASE_PASSWORD=bt_pass
      - DATABASE_NAME=stock_community
    volumes:
      - ../backtest_be_fast:/app
      - backtest_be_fast_venv:/opt/venv
  # Let the image ENTRYPOINT/CMD run (ensures venv is prepared by entrypoint)

  backtest_be_spring:
    build:
      context: ../backtest_be_spring
      dockerfile: Dockerfile
    image: backtest-be-spring:dev
    container_name: backtest_be_spring_dev
    networks:
      - backtest-net
    depends_on:
      - mysql
      - redis
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/stock_community?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=bt_user
      - SPRING_DATASOURCE_PASSWORD=bt_pass
      - SPRING_REDIS_HOST=redis
    volumes:
      - ../backtest_be_spring:/app
      - backtest_be_spring_gradle_cache:/home/gradle/.gradle
    command: ["./gradlew", "bootRun"]

  backtest_fe:
    build:
      context: ../backtest_fe
      dockerfile: Dockerfile.dev
    image: backtest-fe:dev
    container_name: backtest_fe_dev
    networks:
      - backtest-net
    depends_on:
      - backtest_be_fast
      - backtest_be_spring
    ports:
      - "5173:5173"
    volumes:
      - ../backtest_fe:/app
      - backtest_fe_node_modules:/app/node_modules
    environment:
      - VITE_API_URL=http://backtest_be_fast:8000
      - API_PROXY_TARGET=http://backtest_be_fast:8000
    command: ["npm", "run", "dev"]

volumes:
  backtest_db_data_dev:
  backtest_redis_data_dev:
  backtest_fe_node_modules:
  backtest_be_fast_venv:
  backtest_be_spring_gradle_cache:

networks:
  backtest-net:
    name: backtest-network
